version: '3.8'

x-airflow-common: &airflow-common
  build: ./airflow
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
    AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    AIRFLOW_CONN_AWS_S3_CONN: "${AIRFLOW_CONN_AWS_S3_CONN}"
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./data:/opt/data
    - ./scripts:/opt/airflow/scripts
  env_file:
    - ./.env
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres_airflow:
      condition: service_healthy

services:

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      dbt-init:
        condition: service_completed_successfully

  scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      dbt-init:
        condition: service_completed_successfully

  dbt-init:
    <<: *airflow-common
    command: bash -c "airflow db migrate && (airflow users create  --username admin  --firstname admin  --lastname admin  --role Admin  --email admin@example.com  --password admin || true)" #&& cd /opt/airflow/dbt_crypto && dbt deps"

  postgres_airflow:
    image: postgres:13
    volumes:
      - postgres_data_airflow:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U airflow" ]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecom_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_data_airflow:
